config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#land'

  get 'login' => 'home#login', as: :login

  resources :appeals do
    collection do
      get 'stats'
    end
  end

end

app/models/appeal.rb
# == Schema Information
#
# Table name: appeals
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  appeal_type :integer
#  department  :integer
#  subject     :string
#  description :text
#  private     :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Appeal < ActiveRecord::Base
  module AppealType
    REQUEST   = {code: 1, text: "Request"}
    COMPLAINT = {code: 2, text: "Complaint"}
    FEEDBACK  = {code: 3, text: "Feedback"}

    def self.all
      [REQUEST, COMPLAINT, FEEDBACK].collect{|opt| OpenStruct.new opt}
    end

    def self.all_codes
      self.all.collect(&:code)
    end
  end

  module Department
    AGRICULTURE = {code: 1, text: "Agriculture"}
    ENERGY      = {code: 2, text: "Energy"}
    EDUCATION   = {code: 3, text: "Education"}
    FINANCE     = {code: 4, text: "Finance"}
    PLANNING    = {code: 5, text: "Planning"}
    REVENUE     = {code: 6, text: "Revenue"}

    def self.all
      [AGRICULTURE, ENERGY, EDUCATION, FINANCE, PLANNING, REVENUE].collect{|opt| OpenStruct.new opt}
    end

    def self.all_codes
      self.all.collect(&:code)
    end
  end

  attr_accessor :agree_terms

  belongs_to :user

  def department_name
    Department.all.select{|dept| dept.code == self.department}[0].text + " Department"
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  has_many :appeals

  def login=(login)
    @login = login
  end

  def login
    @login || self.pan || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(pan) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end
end

app/controllers/appeals_controller.rb
class AppealsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:public]
      @public_list = true
      @appeals = Appeal.all
    else
      @appeals = current_user.appeals
    end
  end

  def new
    @appeal = current_user.appeals.new
  end

  def create
    @appeal = current_user.appeals.new(appeal_params)
    if @appeal.save
      redirect_to appeals_path, notice: "Appeal submitted successfully"
    else
      render 'edit'
    end
  end

  def show
    @appeal = Appeal.find(params[:id])
  end

  def stats
    
  end

private
  def appeal_params
    params.require(:appeal).permit(:appeal_type, :department, :subject, :description, :private)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :fetch_badge_counts
  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def fetch_badge_counts
    return unless user_signed_in?

    @appeals_count = current_user.appeals.count
    @public_appeals_count = Appeal.count
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:pan, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :pan, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:pan, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def land
    if user_signed_in?
      redirect_to appeals_path
    else
      render layout: "land"
    end
  end

  def login 
  end
end

app/helpers/appeals_helper.rb
module AppealsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  def flash_tag(msg, msg_type)
    return unless msg.present?
    if msg_type == "notice"
      msg_type = "info"
    elsif msg_type == "alert"
      msg_type = "danger"
    end

    content_tag(:div, class: "alert alert-#{msg_type} alert-dismissible", role: "alert") do
      button_tag(class: "close", "data-dismiss" => "alert") do 
        content_tag(:span, raw("&times;"), "aria-hidden" => true) +
          content_tag(:span, "Close", class: "sr-only")
      end + msg
    end
  end

  # +boxes_data+ is an array of hashes with keys: link, text and fa_icon
  def action_links_boxes_tags(boxes_data)
    inner_content = ""
    boxes_data.each_index do |i|
      inner_content += action_link_box_tag(boxes_data[i], i+1)
    end

    content_tag(:div, class: "container-fluid") do
      content_tag(:div, class: "row action-links-boxes") do
        raw inner_content
      end
    end
  end

  def action_link_box_tag(box_data, index)
    content_tag(:div, class: "col-md-4 action-box action-box-#{index}") do
      link_to(raw(box_data[:text] + content_tag(:i, "", class: "fa fa-#{box_data[:fa_icon]}")), box_data[:link])
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def sidebar_link(text, link, fa_class_name, badge_count = nil)
    content_tag(:div, class: "link") do
      content_tag(:span, '', class: "fa fa-#{fa_class_name}") +
        content_tag(:span, badge_count, class: "badge") +
        link_to(text, link)
    end
  end
end

app/views/appeals/_appeal.html.erb
<article class="appeal well">
  <div class="container-fluid">
    <%= link_to "Details", appeal_path(appeal), class: 'details' %>
    <h3><%= appeal.subject %></h3>
    <p>Appealed to <%= appeal.department_name %> on <%= appeal.created_at.strftime('%e %b, %Y') %></p>
  </div>
</article>

app/views/appeals/index.html.erb
<%= link_to "Submit New Appeal", new_appeal_path, class: "page_action" %>
<h1>
  <% if @public_list %>
    Public Appeals
  <% else %>
    My Appeals
  <% end %>
</h1>

<div id="appeals">
  <% if @appeals.any? %>
    <div class="stats well">
      <%= action_links_boxes_tags(
        [
          {
            link: '#',
            text: "<div class='number'>#{@appeals.count}</div><div class='description'>open appeal</div>",
            fa_icon: "external-link"
          },
          {
            link: "#",
            text: "<div class='number'>3</div><div class='description'>actions required</div>",
            fa_icon: "hand-o-up"
          },
          {
            link: "#",
            text: "<div class='number'>3</div><div class='description'>closed appeals</div>",
            fa_icon: "times-circle-o"
          }
        ]
      )
  %>
    </div>
    <%= render @appeals %>
  <% else %>
    <div class="well no-results">
      <p class="container-fluid">
        You did not submit an appeal yet. Get involved by doing one of the following:
      </p>
      <%= action_links_boxes_tags(
            [
              {
                link: new_appeal_path,
                text: "Submit a <br> New Appeal",
                fa_icon: "user"
              },
              {
                link: "#",
                text: "View <br> Public Appeals",
                fa_icon: "users"
              },
              {
                link: "#",
                text: "View <br> MyGovt Stats",
                fa_icon: "line-chart"
              }
            ]
          )
      %>
    </div>
  <% end %>
</div>

app/views/appeals/new.html.erb
<h1>Submit a New Appeal</h1>

<section id="new_appeal" class="well">
  <p class="intro">
    Please be as detailed as possible. Submit all the required documents as attachments. This form will be automatically saved. You can come back later and finish it. Appeals that are not submitted for 30 day after last edit will be automatically deleted.
  </p>
  <%= simple_form_for @appeal do |f| %>
    <%= f.input :appeal_type, collection: Appeal::AppealType.all, label_method: :text, value_method: :code, prompt: "Select the type of your appeal" %>
    <%= f.input :department, collection: Appeal::Department.all, label_method: :text, value_method: :code, prompt: "Select the department your appeal belongs to" %>
    <%= f.input :subject %>
    <%= f.input :description, hint: "Please be as specific as you can" %>
    <%= f.input :private, label: "Keep this appeal private", hint: "Public appeals can be viewed by others and may receive social support" %>
    <%= f.input :agree_terms, as: :boolean, hint: raw("By checking this, you agree that you have read the <a href='#'>Terms &amp; Conditions</a>") %>
    <%= f.submit %>
  <% end %>
</section>

app/views/appeals/show.html.erb
<h1>My Appeal</h1>

<article id="appeal" class="appeal well">
  <%= action_links_boxes_tags(
        [
          {
            link: '#',
            text: "<div class='number'>6</div><div class='description'>days since appeal</div>",
            fa_icon: "plus-circle"
          },
          {
            link: "#",
            text: "<div class='number'>2</div><div class='description'>days since idle</div>",
            fa_icon: "pause"
          },
          {
            link: "#",
            text: "<div class='number'>34</div><div class='description'>days left</div>",
            fa_icon: "question-circle"
          }
        ]
      )
  %>
  <div class="container-fluid">
    <h2><%= @appeal.subject %></h2>
    <div class="description">
      <%= @appeal.description %>

      <section id="track">
        <hr>
        <span class="node node1 done" data-toggle="popover" data-placement="bottom" title="Dispense Clerk" data-content="<dl><dt>In time</dt> <dd>2:34pm July 3, 2015</dd> <dt>Out time</dt> <dd>11:47am July 4, 2015</dd> <dt>Delivery</dt> <dd>1 day in advance</dd> <dt>Comments</dt> <dd>Good to go.</dd> </dl>"></span>
        <span class="node node2 done" data-toggle="popover" data-placement="bottom" title="Range Officer" data-content="<dl> <dt>In time</dt> <dd>11:47am July 4, 2015</dd> <dt>Out time</dt> <dd>12:03am July 4, 2015</dd> <dt>Delivery</dt> <dd>3 day in advance</dd> <dt>Comments</dt> <dd>Forwarding to Divisional Officer.</dd> </dl>"></span>
        <span class="node node3 active" data-toggle="popover" data-placement="bottom" title="Divisional Officer" data-content="<dl> <dt>In time</dt> <dd>12:03am July 4, 2015</dd> <dt>Out time</dt> <dd>N/A</dd> <dt>Delivery</dt> <dd>3 day delayed</dd> <dt>Comments</dt> <dd>Needs conservator's say. Waiting for his word.</dd> </dl>"></span>
        <span class="node node4" data-toggle="popover" data-placement="bottom" title="Conservator" data-content="<dl> <dt>Expected in time</dt> <dd>July 17, 2015</dd> </dl>"></span>
        <span class="node node5" data-toggle="popover" data-placement="bottom" title="Chief Conservator" data-content="<dl> <dt>Expected in time</dt> <dd>July 22, 2015</dd> </dl>"></span>
        <span class="node node6" data-toggle="popover" data-placement="bottom" title="Dispense Clerk" data-content="<dl> <dt>Expected in time</dt> <dd>July 23, 2015</dd> </dl>"></span>
      </section>
      <h3>History:</h3>
      <ul>
        <li>Moved to Mr. John Jaffa (Field Officer) 3 days ago</li>
        <li>Moved to Mr. Sitaiah (Ops Clerk) 4 days ago</li>
        <li>Assigned to Mr. Rajamanikyam (Superintendent) 5 days ago</li>
        <li>Assigned to <%= @appeal.department_name %> 6 days ago</li>
        <li>Appealed 6 days ago</li>
      </ul>
    </div>
  </div>
</article>

app/views/appeals/stats.html.erb
<h1>MyGovt Stats</h1>

<div id="stats" class="well">
  <div class="container-fluid">
    
  </div>

  <div class="container-fluid">
    <div>
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#last-week" aria-controls="home" role="tab" data-toggle="tab">Last Week</a></li>
        <li role="presentation"><a href="#last-month" aria-controls="profile" role="tab" data-toggle="tab">Last Month</a></li>
        <li role="presentation"><a href="#last-year" aria-controls="messages" role="tab" data-toggle="tab">Last Year</a></li>
        <li role="presentation"><a href="#all-time" aria-controls="settings" role="tab" data-toggle="tab">All Time</a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="last-week">
          <%= action_links_boxes_tags(
                [
                  {
                    link: '#',
                    text: "<div class='number'>6</div><div class='description'>appeals submitted</div>",
                    fa_icon: "plus-circle"
                  },
                  {
                    link: "#",
                    text: "<div class='number'>8</div><div class='description'>appeals delivered</div>",
                    fa_icon: "pause"
                  },
                  {
                    link: "#",
                    text: "<div class='number'>79</div><div class='description'>percent discipline</div>",
                    fa_icon: "question-circle"
                  }
                ]
              )
            %>
        </div>
        <div role="tabpanel" class="tab-pane" id="last-month">
          <%= action_links_boxes_tags(
                [
                  {
                    link: '#',
                    text: "<div class='number'>25</div><div class='description'>appeals submitted</div>",
                    fa_icon: "plus-circle"
                  },
                  {
                    link: "#",
                    text: "<div class='number'>18</div><div class='description'>appeals delivered</div>",
                    fa_icon: "pause"
                  },
                  {
                    link: "#",
                    text: "<div class='number'>64</div><div class='description'>percent discipline</div>",
                    fa_icon: "question-circle"
                  }
                ]
              )
            %>
        </div>
        <div role="tabpanel" class="tab-pane" id="last-year">
          <%= action_links_boxes_tags(
                [
                  {
                    link: '#',
                    text: "<div class='number'>306</div><div class='description'>appeals submitted</div>",
                    fa_icon: "plus-circle"
                  },
                  {
                    link: "#",
                    text: "<div class='number'>134</div><div class='description'>appeals delivered</div>",
                    fa_icon: "pause"
                  },
                  {
                    link: "#",
                    text: "<div class='number'>73</div><div class='description'>percent discipline</div>",
                    fa_icon: "question-circle"
                  }
                ]
              )
            %>
        </div>
        <div role="tabpanel" class="tab-pane" id="all-time">
          <%= action_links_boxes_tags(
                [
                  {
                    link: '#',
                    text: "<div class='number'>1297</div><div class='description'>appeals submitted</div>",
                    fa_icon: "plus-circle"
                  },
                  {
                    link: "#",
                    text: "<div class='number'>649</div><div class='description'>appeals delivered</div>",
                    fa_icon: "pause"
                  },
                  {
                    link: "#",
                    text: "<div class='number'>78</div><div class='description'>percent discipline</div>",
                    fa_icon: "question-circle"
                  }
                ]
              )
            %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/common/_head.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Govt</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>

app/views/common/_sidebar.html.erb
<aside>
  <header>
    <h1>My Govt</h1>
    <p class="tagline">Governance. Unleashed.</p>
  </header>

  <section id="links">
    <%= sidebar_link("My Appeals", appeals_path, 'user', @appeals_count) %>
    <%= sidebar_link("Public Appeals", appeals_path(public: true), 'users', @public_appeals_count) %>
    <%= sidebar_link("MyGovt Stats", stats_appeals_path, 'line-chart') %>
  </section>

  <footer>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "logout" %>
    Powered by <a href="http://www.codeastra.com/" target="_blank">Code Astra</a>
  </footer>
</aside>

app/views/home/land.html.erb
<section id="land" class="slide">
  <h1>My Govt</h1>
  <h2>Building Smart Cities through <span id="usp" data-typer-targets="Transparency.,Openness.,"></span></h2>

  <%= link_to "Explore", login_path, id: "explore" %>
</section>

app/views/home/login.html.erb
<%= render "devise/shared/enter" %> 

app/views/layouts/application.html.erb
<%= render partial: 'common/head' %>
<body>
<div id="content_wrapper" class="<%= user_signed_in? ? 'loggedin' : 'guest_user' %>">
  <%= render 'common/sidebar' %>
  <div id="main_content">
    <div class="flash_messages">
      <%= flash_tag(notice, "notice") %>
      <%= flash_tag(alert, "alert") %>
    </div>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/layouts/land.html.erb
<%= render partial: 'common/head' %>
<body>
<%= yield %>

</body>
</html>